name: Makefile CI

on:
  repository_dispatch:
  workflow_dispatch:
 # schedule:
 #   - cron: 0 16 4,9,14,19,24,28,31 * *

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Install dependencies
      run: cd ui && npm install && sudo apt install libpcap-dev

    - name: Run check
      run: echo 'check'

    - name: Run build
      run: make build-ui release

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: openbytes
        tag: ${{ env.FILE_DATE }}
        artifacts: "bundles/*"
        token: ${{ secrets.GITHUB_TOKEN }}