name: Makefile CI

on:
  repository_dispatch:
  workflow_dispatch:
 # schedule:
 #   - cron: 0 16 4,9,14,19,24,28,31 * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: pwd

    - name: Install dependencies
      run: cd ui && npm install && sudo apt install libpcap-dev

    - name: Run check
      run: echo 'check'

    - name: Run distcheck
      run: make build-ui build-go
      

    - name: Release
      uses: ncipollo/release-action@v1
      with:
#       tag: openwrt_JD-AX1800_${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        tag: Openbytes-${{ github.ref }}
        artifacts: bundles/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Enjoy~

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false