name: Makefile CI/CD

on:
  repository_dispatch:
  workflow_dispatch:
 # schedule:
 #   - cron: 0 16 4,9,14,19,24,28,31 * *

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64,arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install libpcap-dev && cd ui && npm install

    - name: Run configure
      run: echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    # - uses: wangyoucao577/go-release-action@v1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     goos: ${{ matrix.goos }}
    #     goarch: ${{ matrix.goarch }}
    #     binary_name: "test-binary"
    #     pre_command: ""
    #     build_command: "make build-go"

    - name: Run build
      run: make build-ui build-go

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: openbytes
        tag: ${{ env.FILE_DATE }}-${{ matrix.goarch }}
        artifacts: "bundles/*"
        token: ${{ secrets.GITHUB_TOKEN }}