name: Makefile CI/CD

on:
  repository_dispatch:
  workflow_dispatch:
 # schedule:
 #   - cron: 0 16 4,9,14,19,24,28,31 * *

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64,arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install libpcap-dev 
        cd ui && npm install && npm run build

    - name: Run configure
      run: echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    # - uses: wangyoucao577/go-release-action@v1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     goos: ${{ matrix.goos }}
    #     goarch: ${{ matrix.goarch }}
    #     binary_name: "test-binary"
    #     pre_command: ""
    #     build_command: "make build-go"

    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu-22.04

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          uname -a
          sudo apt install libpcap-dev
          cd ui && npm install && npm run build
          make build-go

    # - name: Run build
    #   run: |
    #     rm -rf cmd/dist && cp -rf ui/dist cmd/ && rm -rf cmd/dist/js/*.map
    #     go build -o bundles/openbytes-${{ matrix.goos }}-${{ matrix.goarch }} *.go

    # - name: Create Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     name: openbytes-${{ matrix.goarch }}
    #     tag: ${{ matrix.goarch }}${{ env.FILE_DATE }}
    #     artifacts: "bundles/*"
    #     token: ${{ secrets.GITHUB_TOKEN }}