name: release CI/CD

on:
  repository_dispatch:
  workflow_dispatch:
 # schedule:
 #   - cron: 0 16 4,9,14,19,24,28,31 * *

jobs:
  build-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: install depends
      run: |
        sudo apt update
        sudo apt install --yes libpcap-dev
    - name: build
      run: |
        cd ui && npm install && npm run build
        pwd && cd ../
        rm -rf cmd/dist && cp -rf ui/dist cmd/ && rm -rf cmd/dist/js/*.map
        go build -o bundles/openbytes-linux-x86_64 *.go
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: bundles

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: install depends
      run: |
        echo 'nice'
    - name: build
      run: |
        cd ui && npm install && npm run build
        pwd && cd ../
        rm -rf cmd/dist && cp -rf ui/dist cmd/ && rm -rf cmd/dist/js/*.map
        go build -o bundles/openbytes-darwin-arm64 *.go
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: bundles

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: bundles
    - name: version
      run: |
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    - name: release
      uses: ncipollo/release-action@v1
      with:
        name: openbytes
        tag: ${{ env.FILE_DATE }}
        artifacts: "bundles/*"
        token: ${{ secrets.GITHUB_TOKEN }}